#pragma once
#include<Windows.h>
#define CALCM_COMMAND_ENTERED			WM_USER +1
#define CALCM_CHARACTER_ENTERED			WM_USER +2
#define CALCM_ENTER_PRESSED				WM_USER +3
#define CALCM_SHIFT_PRESSED				WM_USER +4
#define CALCM_PROCEDURE_PRESSED			WM_USER +5
#define CALCM_PLUS_MINUS_PRESSED		WM_USER +6
#define CALCM_MODEL_CHANGED				WM_USER +7
#define CALCM_BACKSPACE_ENTERED			WM_USER +8
